# **Preprocesamiento de datos**

In [2]:
# Importar paquetes
import pandas as pd
import numpy as np

**CREAR DATAFRAME**

In [55]:
# Crear diccionario
dic = {'Cedula': [123, 456, 789, 987, 654, 432],
       'Sexo': ['F', 'M', 'F', 'M', 'M', 'F'],
       'Edad': [22, 25, 18, 24, 22, 28],
       'Nota_1': [3.4, 4.6, 3.2, 4.8, 2.1, 4.5],
       'Nota_2': [2.4, 3.8, 4.7, np.nan , 3.4, 4.3],
       'Nota_3': [1.7, 3.5, 3.4, 4.9, 5.0, 4.7]}

# Convertir un diccionario a un DataFrame
df = pd.DataFrame(dic, index = ['Marcela', 'Juan', 'Daniela','Jose', 'Luis', 'Camila'])
df

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0
Camila      432    F    28     4.5     4.3     4.7

In [ ]:
# Acceder a los Ã­ndices del DataFrame
df.index

Index(['Marcela', 'Juan', 'Daniela', 'Jose', 'Luis', 'Camila'], dtype='object')

In [ ]:
# Acceder a las columnas del DataFrame
df.columns

Index(['Cedula', 'Sexo', 'Edad', 'Nota_1', 'Nota_2', 'Nota_3'], dtype='object')

In [ ]:
# Acceder a las dimensiones
df.shape

(6, 6)

In [ ]:
# Acceder a la cantidad de registros
df.size

36

In [ ]:
# Acceder a una matriz con los valores
df.values

array([[123, 'F', 22, 3.4, 2.4, 1.7],
       [456, 'M', 25, 4.6, 3.8, 3.5],
       [789, 'F', 18, 3.2, 4.7, 3.4],
       [987, 'M', 24, 4.8, nan, 4.9],
       [654, 'M', 22, 2.1, 3.4, 5.0],
       [432, 'F', 28, 4.5, 4.3, 4.7]], dtype=object)

In [ ]:
# Acceder a las primeras n filas del dataframe
df.head() # si no pongo un nÃºmero entre el parÃ©ntesis por defecto es 5

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0

In [ ]:
# Acceder a las primeras 3 filas del dataframe
df.head(3)

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4

In [ ]:
# Acceder a las ultimas n filas del dataframe
df.tail() # si no tiene un valor entre el parÃ©ntesis por defecto es 5

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0
Camila      432    F    28     4.5     4.3     4.7

In [ ]:
# Acceder a las ultimas dos filas del dataframe
df.tail(2)

        Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Luis       654    M    22     2.1     3.4     5.0
Camila     432    F    28     4.5     4.3     4.7

In [ ]:
# Acceder a una muestra de filas aleatorias
df.sample() # Si no tiene un valor entre el parÃ©ntesis por defecto es 1

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7

In [ ]:
# Acceder a una muestra de 3 filas aleatorias
df.sample(3)

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan        456    M    25     4.6     3.8     3.5
Jose        987    M    24     4.8     NaN     4.9
Marcela     123    F    22     3.4     2.4     1.7

### **SELECCIONAR COLUMNAS CON PANDAS**

In [ ]:
df['Cedula'] # Seleccionar una sola columna, el resultado queda en formato serie - OpciÃ³n 1

Marcela    123
Juan       456
Daniela    789
Jose       987
Luis       654
Camila     432
Name: Cedula, dtype: int64

In [ ]:
df.Cedula #Se leccionar una sola columna, el resultado queda en formato serie - OpciÃ³n 2

Marcela    123
Juan       456
Daniela    789
Jose       987
Luis       654
Camila     432
Name: Cedula, dtype: int64

In [ ]:
# No se pueden seleccionar mÃ¡s de dos columnas con el mÃ©todo anterior
df['Cedula', 'Nota_1', 'Edad']

KeyError: ignored

In [ ]:
df[['Cedula']] # Seleccionar una sola columna, el resultado queda en formato DataFrame

         Cedula
Marcela     123
Juan        456
Daniela     789
Jose        987
Luis        654
Camila      432

In [ ]:
df[['Cedula', 'Nota_1', 'Edad']] # Seleccionar mÃ¡s de una columna en formato DataFrame

         Cedula  Nota_1  Edad
Marcela     123     3.4    22
Juan        456     4.6    25
Daniela     789     3.2    18
Jose        987     4.8    24
Luis        654     2.1    22
Camila      432     4.5    28

**SELECCIONAR USANDO EL NOMBRE: FUNCIÃN .loc**

In [ ]:
df.loc['Marcela', ['Nota_1','Nota_2']] # Seleccionar una fila y dos columnas

Nota_1    3.4
Nota_2    2.4
Name: Marcela, dtype: object

In [ ]:
df.loc[['Marcela','Jose'], ['Nota_1','Nota_2']] # Seleccionar dos filas y dos columnas

         Nota_1  Nota_2
Marcela     3.4     2.4
Jose        4.8     NaN

In [ ]:
df.loc['Daniela','Edad'] # Seleccionar un dato puntual

18

In [ ]:
df.loc[:, ['Nota_3', 'Nota_1', 'Cedula']] # Seleccionar todas las filas y unas columnas especificas.

         Nota_3  Nota_1  Cedula
Marcela     1.7     3.4     123
Juan        3.5     4.6     456
Daniela     3.4     3.2     789
Jose        4.9     4.8     987
Luis        5.0     2.1     654
Camila      4.7     4.5     432

**SELECCIONAR USANDO LA POSICIÃN: FUNCIÃN .iloc**

In [ ]:
df.iloc[0, [3,4]] # Seleccionar una fila y dos columnas

Nota_1    3.4
Nota_2    2.4
Name: Marcela, dtype: object

In [ ]:
df.iloc[[0, 3], [3,4]] # Seleccionar dos filas y dos columnas

         Nota_1  Nota_2
Marcela     3.4     2.4
Jose        4.8     NaN

In [ ]:
df.iloc[2:6, [3,4]] # Seleccionar un rango de filas y dos columnas

         Nota_1  Nota_2
Daniela     3.2     4.7
Jose        4.8     NaN
Luis        2.1     3.4
Camila      4.5     4.3

In [ ]:
df.iloc[3:, [3,4]] # Seleccionar desde la fila 3 en adelante y dos columnas

        Nota_1  Nota_2
Jose       4.8     NaN
Luis       2.1     3.4
Camila     4.5     4.3

**FILTRAR CON CONDICIONES**

In [ ]:
df['Nota_3'] >= 3.5 # De esta manera imprime una serie con Falso o Verdadero dependiendo si se cumple o no la condiciÃ³n

Marcela    False
Juan        True
Daniela    False
Jose        True
Luis        True
Camila      True
Name: Nota_3, dtype: bool

In [ ]:
df[df['Nota_3'] >= 3.5] # Filtrar DataFrame aplicando una condiciÃ³n

        Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan       456    M    25     4.6     3.8     3.5
Jose       987    M    24     4.8     NaN     4.9
Luis       654    M    22     2.1     3.4     5.0
Camila     432    F    28     4.5     4.3     4.7

In [ ]:
df[(df['Nota_1'] >= 2.5) & (df['Nota_2'] >= 3.5)] # Filtrar mÃ¡s de una condiciÃ³n con el operador AND (&)

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Camila      432    F    28     4.5     4.3     4.7

In [ ]:
df[(df['Nota_1'] >= 2.5) | (df['Nota_2'] >= 3.5)] # Filtrar mÃ¡s de una condiciÃ³n con el operador OR (|)

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Camila      432    F    28     4.5     4.3     4.7

In [ ]:
df[df['Nota_2']>= df['Nota_1']] # Filtrar comparando dos columnas

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Daniela     789    F    18     3.2     4.7     3.4
Luis        654    M    22     2.1     3.4     5.0

In [ ]:
df.query('Nota_3 >= 3.5') # El mÃ©todo query permite no escribir todo el tiempo el nombre del DataFrame

        Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan       456    M    25     4.6     3.8     3.5
Jose       987    M    24     4.8     NaN     4.9
Luis       654    M    22     2.1     3.4     5.0
Camila     432    F    28     4.5     4.3     4.7

In [ ]:
df.query('Nota_1 >= 2.5 & Nota_2 >= 3.5') # Filtrar dos condiciones con el mÃ©todo query

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Camila      432    F    28     4.5     4.3     4.7

**FILTRAR TEXTO**

In [3]:
acc = pd.read_csv('https://www.datos.gov.co/api/views/7cci-nqqb/rows.csv?accessType=DOWNLOAD') # Cargar los datos

**funciÃ³n .str**

In [ ]:
acc[acc['nombrecomuna'].str[0] == '1'].head() # .str Habilita funciones para el DataFrame .str[0] significa la primera letra

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,...,0,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n
10,11,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,2,0,0,...,0,0,CALLE,Sotomayor,06:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Nocturno,No aplica
12,13,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,0,CALLE,Fontana,01:45:00 p.Â m.,AGENTES DTB,10. PROVENZA,Particular,Diurno,Sin restricciÃ³n

In [ ]:
acc[acc['GRAVEDAD'].str[0:3] == 'Con'].head() # Aplicar str con una longitud

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,...,0,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
9,10,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,1,0,0,...,0,0,CARRERA,Tejar Norte,04:35:00 p.Â m.,AGENTES DTB,01. NORTE,Particular,Diurno,No aplica
12,13,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,0,CALLE,Fontana,01:45:00 p.Â m.,AGENTES DTB,10. PROVENZA,Particular,Diurno,Sin restricciÃ³n

In [ ]:
acc[acc['nombrecomuna'].str.contains('LA')].head() # Aplicar str con contener una palabra (Contains es similar a la funciÃ³n like en SQL)

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
10,11,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,2,0,0,...,0,0,CALLE,Sotomayor,06:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Nocturno,No aplica
14,15,03/01/2012,2012,01. Enero,02. Martes,Con Heridos,0,0,0,0,...,0,0,CARRERA,Nuevo Sotomayor,06:45:00 a.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Empresa,Diurno,Sin restricciÃ³n

In [ ]:
acc[acc['nombrecomuna'].str.contains('LA|ZA')].head() # Aplicar contains con OR

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
10,11,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,2,0,0,...,0,0,CALLE,Sotomayor,06:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Nocturno,No aplica
12,13,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,0,CALLE,Fontana,01:45:00 p.Â m.,AGENTES DTB,10. PROVENZA,Particular,Diurno,Sin restricciÃ³n

In [ ]:
acc[acc['nombrecomuna'].str.len()>15].head() # Aplicar un filtro con la longitud del texto

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
7,8,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,2,...,0,0,TRANSVERSAL METROPOLITANA,Bucaramanga,07:20:00 p.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Nocturno,No aplica

**regex**

In [ ]:
acc[acc['DIURNIO/NOCTURNO'].str.contains('^D')].head() # El sÃ­mbolo ^ significa principio

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
8,9,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,1,0,0,...,0,1,CARRERA,Regaderos Norte,12:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica

In [ ]:
acc[acc['VIA 1'].str.contains('A$')].head() # El sÃ­mbolo $ significa fin

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,...,0,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica

**DESCRIBIR DATAFRAME**

In [ ]:
acc.describe().iloc[:,2:] # Muestra caracterÃ­sticas de las variables numÃ©ricas que componen la base de datos

,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,BUSETA,BUS,CAMION,VOLQUETA,MOTO,BICICLETA,OTRO
count,38197.00000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000,38197.000000
mean,0.10472,0.786292,0.060947,0.197555,0.020290,0.044061,0.048198,0.083279,0.014242,0.611697,0.017384,0.021075
std,0.33937,0.743994,0.245928,0.432211,0.141916,0.211639,0.218303,0.287543,0.120025,0.652550,0.132290,0.149355
min,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
75%,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000
max,7.00000,29.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,2.000000,8.000000,3.000000,2.000000

In [ ]:
acc.describe(include = 'all') # Con el parÃ¡metro include = 'all' se muestra informaciÃ³n de las variables de texto

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
count,38197.000000,38197,38197.000000,38197,38197,38197,38197.00000,38197.000000,38197.000000,38197.000000,...,38197.000000,38197.000000,38197,38197,37931,37952,38197,38197,38197,38197
unique,NaN,4050,NaN,12,7,6,NaN,NaN,NaN,NaN,...,NaN,NaN,94,255,1119,3,28,3,2,7
top,NaN,22/12/2018,NaN,03. Marzo,06. Sabado,Solo DaÃ±os,NaN,NaN,NaN,NaN,...,NaN,NaN,CARRERA,Centro,04:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,Sin restricciÃ³n
freq,NaN,26,NaN,3366,6273,19475,NaN,NaN,NaN,NaN,...,NaN,NaN,16430,3774,553,35358,6323,31947,27032,22023
mean,19099.000000,NaN,2016.480430,NaN,NaN,NaN,0.10472,0.786292,0.060947,0.197555,...,0.017384,0.021075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,11026.668453,NaN,3.063243,NaN,NaN,NaN,0.33937,0.743994,0.245928,0.432211,...,0.132290,0.149355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000,NaN,2012.000000,NaN,NaN,NaN,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,9550.000000,NaN,2014.000000,NaN,NaN,NaN,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,19099.000000,NaN,2016.000000,NaN,NaN,NaN,0.00000,1.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,28648.000000,NaN,2019.000000,NaN,NaN,NaN,0.00000,1.000000,0.000000,0.000000,...,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,38197.000000,NaN,2023.000000,NaN,NaN,NaN,7.00000,29.000000,2.000000,3.000000,...,3.000000,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Crear dataframe temporal con los accidentes por barrio
barrio = acc.groupby(['BARRIO'])[['ORDEN']].count().reset_index().rename(columns = {'ORDEN':'ACCIDENTES'})
barrio

                       BARRIO  ACCIDENTES
0    10 DE MAYO SANTA BARBARA           1
1               12 de Octubre           3
2                 13 de junio           6
3                 20 de julio           1
4                 23 de junio           2
..                        ...         ...
250                Villa Rosa          61
251                Villa Sara           5
252     Villas de San Ignacio         131
253               VÃ­a ChimitÃ¡           1
254                 Zarabanda           2

[255 rows x 2 columns]

In [ ]:
# Sacar percentiles de la base de datos anterior
barrio.describe(percentiles = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

        ACCIDENTES
count   255.000000
mean    149.792157
std     380.080638
min       1.000000
20%       2.000000
30%       3.000000
40%       6.000000
50%      13.000000
60%      27.000000
70%      61.800000
80%     163.200000
90%     459.400000
max    3774.000000

In [ ]:
acc.info() # Muestra informaciÃ³n de las variables, como datos NO nulos y tipo de dato

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38197 entries, 0 to 38196
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ORDEN                    38197 non-null  int64
 1   FECHA                    38197 non-null  object
 2   AÃO                      38197 non-null  int64
 3   MES                      38197 non-null  object
 4   DÃA                      38197 non-null  object
 5   GRAVEDAD                 38197 non-null  object
 6   PEATON                   38197 non-null  int64
 7   AUTOMOVIL                38197 non-null  int64
 8   CAMPAERO                 38197 non-null  int64
 9   CAMIONETA                38197 non-null  int64
 10  MICRO                    38197 non-null  int64
 11  BUSETA                   38197 non-null  int64
 12  BUS                      38197 non-null  int64
 13  CAMION                   38197 non-null  int64
 14  VOLQUETA                 38197 non-null  int64
 15  MOTO                     38197 non-null  int64
 16  BICICLETA                38197 non-null  int64
 17  OTRO                     38197 non-null  int64
 18  VIA 1                    38197 non-null  object
 19  BARRIO                   38197 non-null  object
 20  HORA                     37931 non-null  object
 21  ENTIDAD                  37952 non-null  object
 22  nombrecomuna             38197 non-null  object
 23  Propietario de VehÃ­culo  38197 non-null  object
 24  DIURNIO/NOCTURNO         38197 non-null  object
 25  HORA RESTRICCION MOTO    38197 non-null  object
dtypes: int64(14), object(12)
memory usage: 7.6+ MB

In [ ]:
acc.isnull().sum() # Muestra la cantidad de datos nulos por variable

ORDEN                        0
FECHA                        0
AÃO                          0
MES                          0
DÃA                          0
GRAVEDAD                     0
PEATON                       0
AUTOMOVIL                    0
CAMPAERO                     0
CAMIONETA                    0
MICRO                        0
BUSETA                       0
BUS                          0
CAMION                       0
VOLQUETA                     0
MOTO                         0
BICICLETA                    0
OTRO                         0
VIA 1                        0
BARRIO                       0
HORA                       266
ENTIDAD                    245
nombrecomuna                 0
Propietario de VehÃ­culo      0
DIURNIO/NOCTURNO             0
HORA RESTRICCION MOTO        0
dtype: int64

In [ ]:
acc.dtypes # Muestra el tipo de dato

ORDEN                       int64
FECHA                      object
AÃO                         int64
MES                        object
DÃA                        object
GRAVEDAD                   object
PEATON                      int64
AUTOMOVIL                   int64
CAMPAERO                    int64
CAMIONETA                   int64
MICRO                       int64
BUSETA                      int64
BUS                         int64
CAMION                      int64
VOLQUETA                    int64
MOTO                        int64
BICICLETA                   int64
OTRO                        int64
VIA 1                      object
BARRIO                     object
HORA                       object
ENTIDAD                    object
nombrecomuna               object
Propietario de VehÃ­culo    object
DIURNIO/NOCTURNO           object
HORA RESTRICCION MOTO      object
dtype: object

In [ ]:
acc['BARRIO'].unique() # .unique() me permite ver las categorÃ­as de una variable

array(['Mutis', 'Regaderos Norte', 'Cabecera del Llano', 'Norte Bajo',
       'Dangond', 'San Miguel', 'La Pedregosa', 'Bucaramanga',
       'Tejar Norte', 'Sotomayor', 'Fontana', 'Provenza',
       'Nuevo Sotomayor', 'Cafe Madrid', 'Centro', 'Alvarez', 'Asturias',
       'Bolarqui', 'Los Pinos', 'Manuela Beltran', 'Rio de Oro I',
       'Alarcon', 'Real de Minas', 'Antonia Santos Centro', 'Conucos',
       'La Aurora', 'Mejoras Publicas', 'Girardot', 'San Alonso',
       'Juan XXIII', 'La Ceiba', 'Comuneros', 'Antonia Santos Sur',
       'La Concordia', 'PREDIO URBANO PUENTE EL BUENO', 'Divino NiÃ±o',
       'La Victoria', 'San Francisco', 'Lagos del Cacique', 'El Jardin',
       'Colseguros Norte', 'Colorados', 'Miraflores', 'Villa Alicia',
       'SIN INFORMACION', 'Candiles', 'Bolivar', 'El Tejar',
       'CAMINO DEL PARQUE', 'Campo Hermoso', 'Esperanza I',
       'FLORIDABLANCA', 'Universidad', 'San Rafael', 'Ricaurte',
       'Kennedy', 'NUEVO SOTOMAYOR', 'SANTA BARBARA', 'Estoraques I y II',
       'La Estrella', 'San Gerardo', 'Diamante I', 'Alfonso Lopez',
       'Diamante II', 'Puerta del Sol', 'Africa', 'Chapinero',
       'Morrorico', 'El Rocio', 'Modelo', 'Garcia Rovira', 'Gaitan',
       'ANTONIA SANTOS CENTRO', 'Canelos', 'LA CEIBA', 'El Prado',
       'Terrazas', 'Chorreras de Don Juan', 'Toledo Plata', 'ROBLES',
       'El Porvenir', 'SAN GERARDO II', 'Albania', 'Manzanares',
       'La Joya', 'Quebrada la Iglesia II', 'Pan de Azucar',
       'CABECERA DEL LLANO', 'Villa Mercedes', 'Gomez NiÃ±o',
       'Bosque norte', 'La Feria', 'LA CANTERA-EL CERRO',
       'Ciudad Venecia', 'La Salle', 'Antiguo Campestre', 'CONUCOS',
       'Mutualidad', 'Villa Helena I', 'EL TEJAR', 'SAN FRANCISCO',
       'La Floresta', 'NariÃ±o', 'La Libertad', 'La Juventud', 'Olas II',
       'Nueva Granada', 'VIADUCTO LA FLORA(NO BARRIO)', 'CAMPESTRE',
       'Mercedes', 'Santander', 'San Martin', 'Monterredondo',
       'LA ESMERALDA', 'Vijagual', 'LA TRINIDAD', 'VILLA DIAMANTE',
       'San Expedito', 'PEDREGAL', 'Villa Rosa', '13 de junio',
       'LA independencia', 'Galan', 'Los Guayacanes', 'Transicion I-V',
       'GRANADA', 'VILLA HELENA II', 'SOTOMAYOR', 'Cordoncillo II',
       'Delicias', 'SAN ALONSO', 'Quebrada la Iglesia I',
       'PRADOS DEL MUTIS', 'SAN PIO', 'Quinta Dania', 'CALDAS',
       'Villa Diamante', 'La Esmeralda', 'Brisas del Mutis', 'Malpaso',
       'Vegas de Morrorico', 'Buenos Aires', 'NORTE BAJO', 'MODELO',
       'Sauces', 'VEGAS DE MORRORICO', 'LA CONCORDIA', 'Limoncito',
       'Prados del Mutis', 'LA FLORESTA', 'Altos del Progreso',
       'Altos del Lago', 'MUTIS', 'Maria Paz', 'Granada',
       'PUERTA DEL SOL', 'San Luis', 'EL PLAN',
       '10 DE MAYO SANTA BARBARA', 'Altos del Cacique', 'Balconcitos',
       'Lizcano I', 'NAPOLES', 'El Diviso', 'Bosconia', 'Los Heroes',
       'Hacienda San Juan', 'Brisas de Provenza', 'Candado',
       'Villas de San Ignacio', 'Los Angeles', 'El Rosal', 'PORTO FINO',
       'Villa Ines', 'San CristÃ³bal', 'Miramar', 'Pablo VI',
       'Esperanza II', 'Santa Maria', 'EL PRADO', 'LOS ROBLES',
       'MONTERREDONDO', 'Claveriano', 'RUITOQUE', 'Villa Helena II',
       'Minuto de Dios', 'Esperanza III', 'ANTONIA SANTOS SUR',
       'Villa Sara', 'El Pablon', 'Las Hamacas', 'Los Cedros',
       'SAN PEDRO', 'Cordoncillo I', 'Balcones del Kennedy',
       '23 de junio', 'Olas Altas', 'MERCEDES', 'VIJAGUAL', 'MUTUALIDAD',
       'Venado de Oro', 'Jardines de Coaviconsa', 'BUENAVISTA', 'CENTRO',
       'La Gran Ladera', 'SAN LUIS', 'PROVENZA', 'BRISAS DEL MUTIS',
       'LA SALLE', 'Delicias Altas', 'SAN RAFAEL', 'TERRAZAS',
       'Quinta Brigada', 'COMUNEROS', 'Olas Bajas', 'Buenavista',
       'Don Bosco', 'SAN MIGUEL', 'Omaga II', '12 de Octubre',
       'Puerto Rico', 'Cristal Alto', 'LOS ALPES', 'Los Laureles',
       'Altos del Kennedy', 'Rio de Oro II', 'Zarabanda', 'Rosalta',
       'DANGOND', 'Condado de Gibraltar', 'CANDADO',
       'Granjas de Provenza', 'Altos del Jardin', 'Mirador Norte',
       'Pio XII', '20 de julio', 'Miradores del Kennedy', 'San Jose',
       'MIRADORES DE LA CANTERA', 'Las Delicias', 'VÃ­a ChimitÃ¡', 'Robles',
       'Quintadania', 'Quinta Estrella', 'San Cristobal', 'Rosa Blanca',
       'Puente El Bueno', 'Napoles', 'Chorreras Don Juan',
       'La independencia', 'Terminal de Transporte', 'EL BUENO',
       'Rosa blanca', 'Los Conquistadores', 'Estoraques'], dtype=object)

In [ ]:
acc['GRAVEDAD'].unique() # Ejemplo 2 de categorÃ­as

array(['Con Heridos', 'Solo DaÃ±os', 'Con Muertos', 'Con heridos',
       'Solo daÃ±os', 'Con muertos'], dtype=object)

In [ ]:
acc['GRAVEDAD'].value_counts() # Contar las veces que aparece una categorÃ­a

Solo DaÃ±os     19475
Con Heridos    18051
Con Muertos      562
Con heridos       99
Con muertos        6
Solo daÃ±os         4
Name: GRAVEDAD, dtype: int64

**FECHAS**

In [ ]:
type(acc['FECHA'][2]) # Ver el tipo de dato que tiene la columna fecha

str

In [ ]:
acc['FECHA2'] = pd.to_datetime(acc['FECHA'] , format = '%d/%m/%Y') # Convertir la fecha en el formato correcto
type(acc['FECHA2'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [ ]:
acc[['FECHA','FECHA2']].head(3) # Comparar

        FECHA     FECHA2
0  01/01/2012 2012-01-01
1  01/01/2012 2012-01-01
2  01/01/2012 2012-01-01

Una vez la fecha tiene el formato correcto, se puede manipular fÃ¡cilmente y sacar informaciÃ³n adicional

In [ ]:
acc['FECHA2'].dt.year # Sacar el aÃ±o

0        2012
1        2012
2        2012
3        2012
4        2012
         ...
38192    2023
38193    2023
38194    2023
38195    2023
38196    2023
Name: FECHA2, Length: 38197, dtype: int64

In [ ]:
acc['FECHA2'].dt.month # Sacar el mes

0        1
1        1
2        1
3        1
4        1
        ..
38192    2
38193    2
38194    2
38195    2
38196    3
Name: FECHA2, Length: 38197, dtype: int64

In [ ]:
acc['FECHA2'].dt.day # Sacar el dÃ­a

0         1
1         1
2         1
3         1
4         1
         ..
38192     6
38193    15
38194    17
38195    19
38196    11
Name: FECHA2, Length: 38197, dtype: int64

In [ ]:
acc['FECHA2'].dt.hour # Sacar la hora

0        0
1        0
2        0
3        0
4        0
        ..
38192    0
38193    0
38194    0
38195    0
38196    0
Name: FECHA2, Length: 38197, dtype: int64

In [ ]:
acc['FECHA2'].dt.weekday # Sacar el dÃ­a de la semana

0        6
1        6
2        6
3        6
4        6
        ..
38192    0
38193    2
38194    4
38195    6
38196    5
Name: FECHA2, Length: 38197, dtype: int64

In [ ]:
acc['FECHA2'].dt.strftime('%m-%Y') # Sacar el mes y el aÃ±o

0        01-2012
1        01-2012
2        01-2012
3        01-2012
4        01-2012
          ...
38192    02-2023
38193    02-2023
38194    02-2023
38195    02-2023
38196    03-2023
Name: FECHA2, Length: 38197, dtype: object

In [ ]:
acc['FECHA2'].dt.strftime('%a') # Sacar el dÃ­a de la semana en nombre

0        Sun
1        Sun
2        Sun
3        Sun
4        Sun
        ...
38192    Mon
38193    Wed
38194    Fri
38195    Sun
38196    Sat
Name: FECHA2, Length: 38197, dtype: object

**RENOMBRAR COLUMNAS**

In [ ]:
df.head() # Base original

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0

In [ ]:
df = df.rename(columns ={'Nota_3':'Nota_f','Cedula':'IdentificaciÃ³n'}) # Renombrar una columna

In [ ]:
df # Base modificada

         IdentificaciÃ³n Sexo  Edad  Nota_1  Nota_2  Nota_f
Marcela             123    F    22     3.4     2.4     1.7
Juan                456    M    25     4.6     3.8     3.5
Daniela             789    F    18     3.2     4.7     3.4
Jose                987    M    24     4.8     NaN     4.9
Luis                654    M    22     2.1     3.4     5.0
Camila              432    F    28     4.5     4.3     4.7

**BORRAR DATOS**

In [ ]:
acc.head() # Base original

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica,2012-01-01
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-01
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,2012-01-01
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica,2012-01-01
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,...,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n,2012-01-01

In [ ]:
acc.drop([3,4,8]).head(10) # Borrar las filas

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica,2012-01-01
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-01
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,2012-01-01
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n,2012-01-01
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica,2012-01-02
7,8,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,2,...,0,TRANSVERSAL METROPOLITANA,Bucaramanga,07:20:00 p.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Nocturno,No aplica,2012-01-02
9,10,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,1,0,0,...,0,CARRERA,Tejar Norte,04:35:00 p.Â m.,AGENTES DTB,01. NORTE,Particular,Diurno,No aplica,2012-01-02
10,11,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,2,0,0,...,0,CALLE,Sotomayor,06:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Nocturno,No aplica,2012-01-02
11,12,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,0,...,0,AUTOPISTA NORTE,Norte Bajo,08:20:00 a.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,Sin restricciÃ³n,2012-01-02
12,13,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,CALLE,Fontana,01:45:00 p.Â m.,AGENTES DTB,10. PROVENZA,Particular,Diurno,Sin restricciÃ³n,2012-01-02

In [ ]:
acc.drop(['GRAVEDAD','BARRIO'], axis = 1).head() # Borrar columnas, se tiene que especificar axis = 1

,ORDEN,FECHA,AÃO,MES,DÃA,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,...,BICICLETA,OTRO,VIA 1,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
0,1,01/01/2012,2012,01. Enero,07. Domingo,0,1,0,0,0,...,0,0,CALLE,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica,2012-01-01
1,2,01/01/2012,2012,01. Enero,07. Domingo,0,1,0,1,0,...,0,0,VIA MATANZA,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-01
2,3,01/01/2012,2012,01. Enero,07. Domingo,0,0,0,1,0,...,0,0,CARRERA,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,2012-01-01
3,4,01/01/2012,2012,01. Enero,07. Domingo,0,1,0,1,0,...,0,0,CARRERA,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica,2012-01-01
4,5,01/01/2012,2012,01. Enero,07. Domingo,1,0,0,0,0,...,0,0,CARRERA,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n,2012-01-01

In [ ]:
acc.drop(index = [10,34,65], columns = ['MES','DÃA']).head() # Borrar filas y columnas a la vez

,ORDEN,FECHA,AÃO,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,BUSETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
0,1,01/01/2012,2012,Con Heridos,0,1,0,0,0,0,...,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica,2012-01-01
1,2,01/01/2012,2012,Solo DaÃ±os,0,1,0,1,0,0,...,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-01
2,3,01/01/2012,2012,Solo DaÃ±os,0,0,0,1,0,0,...,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,2012-01-01
3,4,01/01/2012,2012,Solo DaÃ±os,0,1,0,1,0,0,...,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica,2012-01-01
4,5,01/01/2012,2012,Con Heridos,1,0,0,0,0,0,...,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n,2012-01-01

In [ ]:
acc.drop(range(100)).head(10) # Borrar las primeras 100 filas (de la posiciÃ³n 0 a la 99 creando un rango)

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
100,101,12/01/2012,2012,01. Enero,04. Jueves,Con Heridos,1,0,0,0,...,0,CALLE,Campo Hermoso,06:45:00 p.Â m.,AGENTES DTB,05. GARCIA ROVIRA,Particular,Nocturno,Sin restricciÃ³n,2012-01-12
101,102,12/01/2012,2012,01. Enero,04. Jueves,Solo DaÃ±os,0,0,0,1,...,0,CARRERA,Centro,03:10:00 p.Â m.,AGENTES DTB,15. CENTRO,Empresa,Diurno,No aplica,2012-01-12
102,103,12/01/2012,2012,01. Enero,04. Jueves,Con Heridos,0,1,0,0,...,0,CALLE,Mejoras Publicas,06:30:00 p.Â m.,AGENTES DTB,13. ORIENTAL,Particular,Nocturno,Sin restricciÃ³n,2012-01-12
103,104,12/01/2012,2012,01. Enero,04. Jueves,Solo DaÃ±os,0,0,0,0,...,0,CALLE,Esperanza I,08:10:00 a.Â m.,AGENTES DTB,02. NORORIENTAL,Particular,Diurno,No aplica,2012-01-12
104,105,13/01/2012,2012,01. Enero,05. Viernes,Con Heridos,0,0,0,1,...,0,CALLE 45 VIA CHIMITA,Rio de Oro I,05:45:00 p.Â m.,AGENTES DTB,04. OCCIDENTAL,Empresa,Diurno,Sin restricciÃ³n,2012-01-13
105,106,13/01/2012,2012,01. Enero,05. Viernes,Solo DaÃ±os,0,0,0,0,...,1,AUTOPISTA NORTE,Norte Bajo,12:30:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-13
106,107,13/01/2012,2012,01. Enero,05. Viernes,Solo DaÃ±os,0,0,0,2,...,0,ANILLO VIAL,Rio de Oro I,05:20:00 a.Â m.,AGENTES DTB,04. OCCIDENTAL,Empresa,Nocturno,No aplica,2012-01-13
107,108,13/01/2012,2012,01. Enero,05. Viernes,Solo DaÃ±os,0,2,0,0,...,0,TRANSVERSAL METROPOLITANA,Real de Minas,06:55:00 a.Â m.,AGENTES DTB,07. LA CIUDADELA,Empresa,Diurno,No aplica,2012-01-13
108,109,13/01/2012,2012,01. Enero,05. Viernes,Con Heridos,0,0,1,0,...,0,BOULEVAR BOLIVAR,San Francisco,03:45:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Empresa,Diurno,Sin restricciÃ³n,2012-01-13
109,110,13/01/2012,2012,01. Enero,05. Viernes,Solo DaÃ±os,0,1,0,0,...,0,ANILLO VIAL,FLORIDABLANCA,06:20:00 p.Â m.,AGENTES DTB,FLORIDABLANCA,Empresa,Nocturno,No aplica,2012-01-13

**BORRAR CON CONDICIONES**

In [4]:
acc.GRAVEDAD

0        Con Heridos
1         Solo DaÃ±os
2         Solo DaÃ±os
3         Solo DaÃ±os
4        Con Heridos
            ...
38192    Con muertos
38193    Con muertos
38194    Con muertos
38195    Con muertos
38196    Con muertos
Name: GRAVEDAD, Length: 38197, dtype: object

In [23]:
acc['GRAVEDAD'] == 'Con Heridos'

0         True
1        False
2        False
3        False
4         True
         ...
38192    False
38193    False
38194    False
38195    False
38196    False
Name: GRAVEDAD, Length: 38197, dtype: bool

In [30]:
acc[acc['GRAVEDAD'] == 'Con Heridos']

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
0,1,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,0,1,0,0,...,0,0,CALLE,Mutis,12:15:00 p.Â m.,AGENTES DTB,17. MUTIS,Particular,Diurno,No aplica
4,5,01/01/2012,2012,01. Enero,07. Domingo,Con Heridos,1,0,0,0,...,0,0,CARRERA,Dangond,12:30:00 a.Â m.,AGENTES DTB,11. SUR,Particular,Nocturno,En restricciÃ³n
6,7,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,1,0,0,0,...,0,0,CARRERA,La Pedregosa,01:50:00 p.Â m.,AGENTES DTB,09. LA PEDREGOSA,Empresa,Diurno,No aplica
9,10,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,1,0,0,...,0,0,CARRERA,Tejar Norte,04:35:00 p.Â m.,AGENTES DTB,01. NORTE,Particular,Diurno,No aplica
12,13,02/01/2012,2012,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,0,CALLE,Fontana,01:45:00 p.Â m.,AGENTES DTB,10. PROVENZA,Particular,Diurno,Sin restricciÃ³n
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38068,38069,30/01/2023,2023,01. Enero,01. Lunes,Con Heridos,0,0,0,0,...,0,0,CARRERA,Centro,08:30:00 p.Â m.,AGENTES DTB,15. CENTRO,Particular,Nocturno,Sin restricciÃ³n
38069,38070,31/01/2023,2023,01. Enero,02. Martes,Con Heridos,0,1,0,0,...,0,0,AVENIDA GONZALEZ VALENCIA,Cabecera del Llano,10:00:00 a.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,Sin restricciÃ³n
38070,38071,31/01/2023,2023,01. Enero,02. Martes,Con Heridos,0,1,0,0,...,0,0,CARRERA,Antiguo Campestre,12:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Empresa,Diurno,Sin restricciÃ³n
38071,38072,31/01/2023,2023,01. Enero,02. Martes,Con Heridos,1,0,0,0,...,0,0,CARRERA,Universidad,12:00:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Diurno,Sin restricciÃ³n
38072,38073,31/01/2023,2023,01. Enero,02. Martes,Con Heridos,0,0,0,0,...,0,0,CALLE,SIN INFORMACION,09:35:00 a.Â m.,AGENTES DTB,SIN INFORMACION,Empresa,Diurno,Sin restricciÃ³n

In [31]:
acc[acc['GRAVEDAD'] == 'Con Heridos'].index

Int64Index([    0,     4,     6,     9,    12,    13,    14,    18,    24,
               26,
            ...
            38063, 38064, 38065, 38066, 38067, 38068, 38069, 38070, 38071,
            38072],
           dtype='int64', length=18051)

In [32]:
lista = acc[acc['GRAVEDAD'] == 'Con Heridos'].index # Definir una lista con las condiciones

In [33]:
lista

Int64Index([    0,     4,     6,     9,    12,    13,    14,    18,    24,
               26,
            ...
            38063, 38064, 38065, 38066, 38067, 38068, 38069, 38070, 38071,
            38072],
           dtype='int64', length=18051)

In [34]:
acc.drop(lista)

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,BICICLETA,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n
7,8,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,2,...,0,0,TRANSVERSAL METROPOLITANA,Bucaramanga,07:20:00 p.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Nocturno,No aplica
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38192,38193,06/02/2023,2023,02. Febrero,01. Lunes,Con muertos,0,0,0,0,...,0,0,AUTOPISTA FLORIDA,Diamante II,01:10:00 a.Â m.,AGENTES DE TRANSITO DTB,10. PROVENZA,Particular,Nocturno,Sin informacion
38193,38194,15/02/2023,2023,02. Febrero,03. Miercoles,Con muertos,0,0,0,0,...,0,0,ANILLO VIAL,Rio de Oro I,03:40:00 p.Â m.,AGENTES DE TRANSITO DTB,04. OCCIDENTAL,Particular,Diurno,Sin informacion
38194,38195,17/02/2023,2023,02. Febrero,05. Viernes,Con muertos,0,0,0,0,...,0,0,AVENIDA Q SECA,San Alonso,03:15:00 a.Â m.,AGENTES DE TRANSITO DTB,13. ORIENTAL,Empresa,Nocturno,Sin informacion
38195,38196,19/02/2023,2023,02. Febrero,07. Domingo,Con muertos,0,0,0,0,...,0,0,CALLE,Campo Hermoso,11:30:00 p.Â m.,AGENTES DE TRANSITO DTB,05. GARCIA ROVIRA,Particular,Nocturno,Sin informacion
38196,38197,11/03/2023,2023,03. Marzo,06. Sabado,Con muertos,0,0,0,0,...,0,0,VIA MATANZA,SIN INFORMACION,04:45:00 a.Â m.,AGENTES DE TRANSITO DTB,SIN INFORMACION,Particular,Nocturno,Sin informacion

In [35]:
df0 = acc.drop(lista) # Aplicar filtro
df0.GRAVEDAD.value_counts()

Solo DaÃ±os     19475
Con Muertos      562
Con heridos       99
Con muertos        6
Solo daÃ±os         4
Name: GRAVEDAD, dtype: int64

In [39]:
lista = acc[(acc['GRAVEDAD'] == 'Con Heridos') | (acc['GRAVEDAD'] == 'Con heridos') ].index
lista

Int64Index([    0,     4,     6,     9,    12,    13,    14,    18,    24,
               26,
            ...
            38180, 38181, 38182, 38183, 38184, 38185, 38186, 38187, 38188,
            38189],
           dtype='int64', length=18150)

In [40]:
df0 = acc.drop(lista) # Aplicar filtro
df0.GRAVEDAD.value_counts()

Solo DaÃ±os     19475
Con Muertos      562
Con muertos        6
Solo daÃ±os         4
Name: GRAVEDAD, dtype: int64

In [47]:
acc['GRAVEDAD2'] = acc['GRAVEDAD'].apply(lambda x: x.lower())
lista = acc[(acc['GRAVEDAD2'] == 'con heridos')].index
lista

Int64Index([    0,     4,     6,     9,    12,    13,    14,    18,    24,
               26,
            ...
            38180, 38181, 38182, 38183, 38184, 38185, 38186, 38187, 38188,
            38189],
           dtype='int64', length=18150)

In [49]:
df0 = acc.drop(lista) # Aplicar filtro
df0.GRAVEDAD2.value_counts()

solo daÃ±os     19479
con muertos      568
Name: GRAVEDAD2, dtype: int64

In [ ]:
acc[acc['GRAVEDAD'] != 'Con Heridos'] #opciÃ³n 2: filtrar el dataframe

,FECHA,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,MICRO,BUSETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,FECHA2
1,01/01/2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,0,0,...,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,2012-01-01
2,01/01/2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,0,0,...,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,2012-01-01
5,01/01/2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,0,0,...,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n,2012-01-01
7,02/01/2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,2,0,0,...,0,TRANSVERSAL METROPOLITANA,Bucaramanga,07:20:00 p.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Nocturno,No aplica,2012-02-01
10,02/01/2012,01. Enero,01. Lunes,Solo DaÃ±os,0,2,0,0,0,0,...,0,CALLE,Sotomayor,06:30:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Nocturno,No aplica,2012-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36589,27/04/2022,04. Abril,03. MiÃ©rcoles,Solo DaÃ±os,0,1,0,0,0,0,...,0,CALLE,Antonia Santos Centro,09:50:00 a.Â m.,AGENTES DTB,13. ORIENTAL,Particular,Diurno,Sin restricciÃ³n,2022-04-27
36591,28/04/2022,04. Abril,04. Jueves,Solo DaÃ±os,0,1,0,0,0,0,...,0,CALLE,Quebrada la Iglesia II,11:50:00 a.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Diurno,Sin restricciÃ³n,2022-04-28
36598,29/04/2022,04. Abril,05. Viernes,Solo DaÃ±os,0,2,0,0,0,0,...,0,CALLE,Ricaurte,06:30:00 a.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Diurno,Sin restricciÃ³n,2022-04-29
36600,29/04/2022,04. Abril,05. Viernes,Solo DaÃ±os,0,1,0,0,0,0,...,1,BOULEVAR BOLIVAR,San Francisco,07:10:00 a.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Diurno,Sin restricciÃ³n,2022-04-29
36604,30/04/2022,04. Abril,06. SÃ¡bado,Solo DaÃ±os,0,2,0,0,0,0,...,0,CALLE,Centro,12:30:00 p.Â m.,AGENTES DTB,15. CENTRO,Particular,Diurno,Sin restricciÃ³n,2022-04-30

In [50]:
acc[(acc['GRAVEDAD'] != 'Con Heridos') & (acc['GRAVEDAD'] != 'Con heridos')] #opciÃ³n 2: filtrar el dataframe

,ORDEN,FECHA,AÃO,MES,DÃA,GRAVEDAD,PEATON,AUTOMOVIL,CAMPAERO,CAMIONETA,...,OTRO,VIA 1,BARRIO,HORA,ENTIDAD,nombrecomuna,Propietario de VehÃ­culo,DIURNIO/NOCTURNO,HORA RESTRICCION MOTO,GRAVEDAD2
1,2,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,VIA MATANZA,Regaderos Norte,02:00:00 p.Â m.,AGENTES DTB,02. NORORIENTAL,Empresa,Diurno,No aplica,solo daÃ±os
2,3,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,0,0,1,...,0,CARRERA,Cabecera del Llano,12:00:00 p.Â m.,AGENTES DTB,12. CABECERA DEL LLANO,Particular,Diurno,No aplica,solo daÃ±os
3,4,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,1,...,0,CARRERA,Norte Bajo,06:30:00 p.Â m.,AGENTES DTB,03. SAN FRANCISCO,Particular,Nocturno,No aplica,solo daÃ±os
5,6,01/01/2012,2012,01. Enero,07. Domingo,Solo DaÃ±os,0,1,0,0,...,0,CALLE,San Miguel,09:10:00 p.Â m.,AGENTES DTB,06. LA CONCORDIA,Particular,Nocturno,Sin restricciÃ³n,solo daÃ±os
7,8,02/01/2012,2012,01. Enero,01. Lunes,Solo DaÃ±os,0,0,0,2,...,0,TRANSVERSAL METROPOLITANA,Bucaramanga,07:20:00 p.Â m.,AGENTES DTB,08. SUROCCIDENTE,Particular,Nocturno,No aplica,solo daÃ±os
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38192,38193,06/02/2023,2023,02. Febrero,01. Lunes,Con muertos,0,0,0,0,...,0,AUTOPISTA FLORIDA,Diamante II,01:10:00 a.Â m.,AGENTES DE TRANSITO DTB,10. PROVENZA,Particular,Nocturno,Sin informacion,con muertos
38193,38194,15/02/2023,2023,02. Febrero,03. Miercoles,Con muertos,0,0,0,0,...,0,ANILLO VIAL,Rio de Oro I,03:40:00 p.Â m.,AGENTES DE TRANSITO DTB,04. OCCIDENTAL,Particular,Diurno,Sin informacion,con muertos
38194,38195,17/02/2023,2023,02. Febrero,05. Viernes,Con muertos,0,0,0,0,...,0,AVENIDA Q SECA,San Alonso,03:15:00 a.Â m.,AGENTES DE TRANSITO DTB,13. ORIENTAL,Empresa,Nocturno,Sin informacion,con muertos
38195,38196,19/02/2023,2023,02. Febrero,07. Domingo,Con muertos,0,0,0,0,...,0,CALLE,Campo Hermoso,11:30:00 p.Â m.,AGENTES DE TRANSITO DTB,05. GARCIA ROVIRA,Particular,Nocturno,Sin informacion,con muertos
38196,38197,11/03/2023,2023,03. Marzo,06. Sabado,Con muertos,0,0,0,0,...,0,VIA MATANZA,SIN INFORMACION,04:45:00 a.Â m.,AGENTES DE TRANSITO DTB,SIN INFORMACION,Particular,Nocturno,Sin informacion,con muertos

**CREAR COPIA DATAFRAME**

In [56]:
df

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0
Camila      432    F    28     4.5     4.3     4.7

In [57]:
df2 = df # Cuando se pone un "=" los dos DataFrame quedan vinculados y un cambio de uno se refleja en el otro

In [58]:
df2

         Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela     123    F    22     3.4     2.4     1.7
Juan        456    M    25     4.6     3.8     3.5
Daniela     789    F    18     3.2     4.7     3.4
Jose        987    M    24     4.8     NaN     4.9
Luis        654    M    22     2.1     3.4     5.0
Camila      432    F    28     4.5     4.3     4.7

In [59]:
df2.iloc[0,0]

123

In [60]:
df2.iloc[0,0]='changed' # Cambiar una celda en el DataFrame nuevo
df2

          Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela  changed    F    22     3.4     2.4     1.7
Juan         456    M    25     4.6     3.8     3.5
Daniela      789    F    18     3.2     4.7     3.4
Jose         987    M    24     4.8     NaN     4.9
Luis         654    M    22     2.1     3.4     5.0
Camila       432    F    28     4.5     4.3     4.7

In [61]:
df # Ver como el cambio se aplica en el DataFrame original

          Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela  changed    F    22     3.4     2.4     1.7
Juan         456    M    25     4.6     3.8     3.5
Daniela      789    F    18     3.2     4.7     3.4
Jose         987    M    24     4.8     NaN     4.9
Luis         654    M    22     2.1     3.4     5.0
Camila       432    F    28     4.5     4.3     4.7

In [62]:
df3 = df.copy()

In [63]:
df3.iloc[0,1]

'F'

In [64]:
df3.iloc[0,1]='changed2'
df3

          Cedula      Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela  changed  changed2    22     3.4     2.4     1.7
Juan         456         M    25     4.6     3.8     3.5
Daniela      789         F    18     3.2     4.7     3.4
Jose         987         M    24     4.8     NaN     4.9
Luis         654         M    22     2.1     3.4     5.0
Camila       432         F    28     4.5     4.3     4.7

In [65]:
df

          Cedula Sexo  Edad  Nota_1  Nota_2  Nota_3
Marcela  changed    F    22     3.4     2.4     1.7
Juan         456    M    25     4.6     3.8     3.5
Daniela      789    F    18     3.2     4.7     3.4
Jose         987    M    24     4.8     NaN     4.9
Luis         654    M    22     2.1     3.4     5.0
Camila       432    F    28     4.5     4.3     4.7

En la siguiente pÃ¡gina se encuentra una discusiÃ³n de por quÃ© no debe hacerse de esta manera una copia del DataFrame:  https://stackoverflow.com/questions/27673231/why-should-i-make-a-copy-of-a-data-frame-in-pandas

Para evitar lo anterior se debe utilizar el mÃ©todo .copy(), el cual creara un backup de la informaciÃ³n sin quedar vinculado a la primera base