# **LECTURA DE DATOS**

La lectura de datos en python se puede hacer de diferentes formas, aqui veremos algunas de las principales, además de los principales formatos en los que puede estar almacenada la información

**INPUT**

In [1]:
# Python proporciona una función integrada input() para leer una línea de texto de la entrada estándar
edad = input('Ingresa tu edad: ')
print('La edad que tienes es:', edad)
type(edad) # Tipo de dato, siempre que se ingresa un dato con input queda guardado como texto

Ingresa tu edad: 28
La edad que tienes es: 28

str

In [2]:
# Para guardar el dato en formato entero o flotante
edad = int(input('Ingresa tu edad: ')) # se puede poner int o float
print('La edad que tienes es:', edad)
type(edad) # Tipo de dato, siempre que se ingresa un dato con input queda guardado como texto

Ingresa tu edad: 28
La edad que tienes es: 28

int

**SUBIR ARCHIVOS LOCALES**

In [3]:
from google.colab import files # Importar Modulo
# https://www.datos.gov.co/Vivienda-Ciudad-y-Territorio/Indicadores-Sectoriales-Distrito-Barranquilla/9f9i-9qsj/data
uploaded = files.upload() # El método files.upload devolverá un diccionario de los archivos que se han subido.

Saving Indicadores_Sectoriales_Distrito_Barranquilla.csv to Indicadores_Sectoriales_Distrito_Barranquilla.csv

In [4]:
import pandas as pd # En particular, ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales. 
import io # leer el .csv cargado con Pandas y decodificarlo para que sea legible
df = pd.read_csv(io.StringIO(uploaded['Indicadores_Sectoriales_Distrito_Barranquilla.csv'].decode('utf-8')), sep = ',')
df.head(5)

,Formato,SECTOR,INDICADOR,2006,2007,2008,2009,2010,2011,2012,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA,"1,795,060","1,820,862","1,846,589","1,872,334","1,898,007","1,923,698","1,949,264",...,"2,049,949","2,074,592","2,048,493","2,131,544","2,199,507","2,239,103",NaN,NaN,NaN,NaN
1,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Barranq...,"1,154,642","1,162,855","1,170,940","1,178,827","1,186,412","1,193,667","1,200,513",...,"1,223,616","1,228,271","1,206,319","1,243,056","1,274,250","1,297,082",NaN,NaN,NaN,NaN
2,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Soledad,"476,296","490,922","505,612","520,504","535,642","551,082","566,784",...,"632,183","649,111","603,999","638,065","665,021","677,070",NaN,NaN,NaN,NaN
3,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Malambo,"103,311","105,312","107,298","109,292","111,270","113,268","115,274",...,"123,265","125,248","128,203","134,468","139,566","142,095",NaN,NaN,NaN,NaN
4,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Puerto ...,"27,793","27,745","27,693","27,629","27,552","27,472","27,393",...,"26,989","26,869","49,264","51,695","53,649","54,621",NaN,NaN,NaN,NaN

**IMPORTAR DATOS DESDE DRIVE**

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**CSV**

In [6]:
df = pd.read_csv('/content/drive/MyDrive/Introducción a la analítica/datos/Indicadores_Sectoriales_Distrito_Barranquilla.csv', sep = ',')
df.head(3)

,Formato,SECTOR,INDICADOR,2006,2007,2008,2009,2010,2011,2012,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA,"1,795,060","1,820,862","1,846,589","1,872,334","1,898,007","1,923,698","1,949,264",...,"2,049,949","2,074,592","2,048,493","2,131,544","2,199,507",NaN,NaN,NaN,NaN,NaN
1,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Barranq...,"1,154,642","1,162,855","1,170,940","1,178,827","1,186,412","1,193,667","1,200,513",...,"1,223,616","1,228,271","1,206,319","1,243,056","1,274,250",NaN,NaN,NaN,NaN,NaN
2,ESTADISTICA GENERAL,DEMOGRAFIA,POBLACION AREA METROPOLITANA Población Soledad,"476,296","490,922","505,612","520,504","535,642","551,082","566,784",...,"632,183","649,111","603,999","638,065","665,021",NaN,NaN,NaN,NaN,NaN

**EXCEL**

In [7]:
pyp = pd.read_excel('/content/drive/MyDrive/Introducción a la analítica/datos/pico_placa.xlsx')
pyp.head(3)

       fecha        vehículos            motos
0 2015-01-01  sin_restriccion  sin_restriccion
1 2015-01-02  sin_restriccion  sin_restriccion
2 2015-01-03  sin_restriccion  sin_restriccion

**TSV: SEPARADO POR TABULACIONES**

In [8]:
acc= pd.read_csv('/content/drive/MyDrive/Introducción a la analítica/datos/accidentalidad_con_motos_municipio_de_Medell_n_a_o_2019.tsv', sep = "\t")
acc.head(3)

,RADICADO,AÑO_ACCIDENTE,FECHA_ACCIDENTE,HORA_ACCIDENTE,CLASE_ACCIDENTE,GRAVEDAD_ACCIDENTE,DIRECCION,ZONA,Diseño Vía
0,1470349,2015,01/01/2015 12:00:00 AM,00:30:00,Choque,HERIDO,Calle 113 Con Carrera 75,COMUNA 7,Tramo de via
1,1470356,2015,01/01/2015 12:00:00 AM,01:00:00,Caida Ocupante,HERIDO,Carrera 64 C Con Calle 80,COMUNA 7,Tramo de via
2,1470357,2015,01/01/2015 12:00:00 AM,02:00:00,Otro,HERIDO,Carrera 36 Con Calle 92 A,COMUNA 3,Tramo de via

**JSON**

Los tipos de datos disponibles con JSON son:

Números: Se permiten negativos y pueden contener parte fraccional separada por puntos. Ejemplo: 123.456

Cadenas: Representan secuencias de cero o más caracteres. Se ponen entre doble comilla y se permiten cadenas de escape. Ejemplo: "Hola"

Booleanos: Representan valores booleanos y pueden tener dos valores: true y false

null: Representan el valor nulo.

Array: Representa una lista ordenada de cero o más valores los cuales pueden ser de cualquier tipo. Los valores se separan por comas y el vector se mete entre corchetes. Ejemplo ["juan","pedro","jacinto"]

Objetos: Son colecciones no ordenadas de pares de la forma <nombre>:<valor> separados por comas y puestas entre llaves. El nombre tiene que ser una cadena entre comillas dobles. El valor puede ser de cualquier tipo.

In [9]:
{
  "departamento":8,
  "nombredepto":"Ventas",
  "director": "Juan Rodríguez",
  "empleados":[
    {
      "nombre":"Pedro",
      "apellido":"Fernández"
    },{
      "nombre":"Jacinto",
      "apellido":"Benavente"
    } 
  ]
}

{'departamento': 8,
 'nombredepto': 'Ventas',
 'director': 'Juan Rodríguez',
 'empleados': [{'nombre': 'Pedro', 'apellido': 'Fernández'},
  {'nombre': 'Jacinto', 'apellido': 'Benavente'}]}

In [10]:
from pandas.io.json import json_normalize
import json
with open('/content/drive/MyDrive/Introducción a la analítica/datos/accidentalidad_georreferenciada_2018.geojson') as f:
  data = json.load(f)
x = json_normalize(data['features'])
x.head(3)

<ipython-input-10-e94ddbc46864>:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  x = json_normalize(data['features'])

,type,properties.OBJECTID,properties.RADICADO,properties.FECHA,properties.HORA,properties.DIA,properties.PERIODO,properties.CLASE,properties.DIRECCION,properties.DIRECCION_ENC,...,properties.DISENO,properties.DIA_NOMBRE,properties.MES,properties.MES_NOMBRE,properties.X_MAGNAMED,properties.Y_MAGNAMED,properties.LONGITUD,properties.LATITUD,geometry.type,geometry.coordinates
0,Feature,549556,1611786,2018/01/02 00:00:00+00,03:18:00,02,2018,Atropello,CR 64 C CL 103 GG,CR 064 C 103 GG 000 00000,...,Tramo de via,MARTES,01,None,835295.93,1188611.46,-75.565634,6.299676,Point,"[-75.5656343110058, 6.299675608847877]"
1,Feature,549558,1611859,2018/01/02 00:00:00+00,05:10:00,02,2018,Choque,CR 75 CL 59,CR 075 059 000 00000,...,Tramo de via,MARTES,01,None,832480.16,1185167.89,-75.591074,6.268543,Point,"[-75.59107386499784, 6.268543464483542]"
2,Feature,549559,1611705,2018/01/02 00:00:00+00,05:26:00,02,2018,Otro,CR 43 A CL 17,CR 043 A 017 000 00000,...,Lote o Predio,MARTES,01,None,834853.96,1179697.78,-75.569627,6.219092,Point,"[-75.5696268821998, 6.219091721355393]"

In [11]:
json_normalize(data) # si lo hubieramos hecho sobre el dataframe directo todo el diccionario de features quedaria en una celda

<ipython-input-11-1c283760bfe1>:1: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead.
  json_normalize(data)

,type,name,features,crs.type,crs.properties.name
0,FeatureCollection,Accidentalidad_georreferenciada_2018,"[{'type': 'Feature', 'properties': {'OBJECTID'...",name,urn:ogc:def:crs:OGC:1.3:CRS84

**DESDE UN SITIO WEB**

In [12]:
acc= pd.read_csv('https://www.datos.gov.co/api/views/yb9r-2dsi/rows.csv?accessType=DOWNLOAD', nrows= 10, usecols = [0,1,2])
# nrows = 1000 importar solo las primeras 1000 filas
# usecols = [0,1,2] importar columnas especificas
acc

          FECHA_ACCIDENTE  AÑO_ACCIDENTE MES_ACCIDENTE
0  01/01/2015 12:00:00 AM           2015         enero
1  01/01/2015 12:00:00 AM           2015         enero
2  01/01/2015 12:00:00 AM           2015         enero
3  01/01/2015 12:00:00 AM           2015         enero
4  01/01/2015 12:00:00 AM           2015         enero
5  01/01/2015 12:00:00 AM           2015         enero
6  01/01/2015 12:00:00 AM           2015         enero
7  01/02/2015 12:00:00 AM           2015         enero
8  01/02/2015 12:00:00 AM           2015         enero
9  01/02/2015 12:00:00 AM           2015         enero

**DESDE BIGQUERY**

**PASOS:**

Cuenta de servicio
- Ir en el menu principal a **API y servicios**
- Dar click en la parte superior **CREAR CREDENCIALES**
- Seleccionar **cuenta de servicio** (service account)
> - Asignar un nombre: es libre
> - Descripción de la cuenta de servicio: es libre
- Dar click en **CREAR Y CONTINUAR**
- Seleccionar el rol que va tener la cuenta, el rol son conjuntos de permisos, ejemplo: Básico-Propietario
- El tercer paso dejarlo vacio
- Dar click en **LISTO**

- Dar click en el **correo de la cuenta de servicio** creada
- En el menu de arriba dar click en **CLAVES**
- Dar click en **AGREGAR CLAVE**
- Dar click en **Crear clave nueva**
- Seleccionar JSON y darle **crear**

In [13]:
# librerias para trabajar con bigquery
#!pip install --upgrade google-cloud-bigquery
from google.cloud import bigquery 
from google.oauth2 import service_account

credentials_path = 'escribir ruta de las credenciales'   # direccion local de archivo JSON con las credenciales del proyecto        
credentials = service_account.Credentials.from_service_account_file(credentials_path)  # asignar las credenciales a la service account 
      
project_id = 'escribir ruta del id del proyecto' # id del projecto
client = bigquery.Client(credentials= credentials, project=project_id) # creacion del client para trabajar en python

In [14]:
# hacer queries sobre los datos
query = "SELECT * FROM `curso4-379521.hurto.hurto_carro` LIMIT 1000"  
df = client.query(query).to_dataframe() 
df

,fecha_hecho,cantidad,latitud,longitud,sexo,edad,estado_civil,grupo_actor,actividad_delictiva,parentesco,...,lugar,sede_receptora,bien,categoria_bien,grupo_bien,modelo,color,permiso,unidad_medida,fecha_ingestion
0,2019-01-30 15:30:00+00:00,1.0,6.280306,-75.612912,Mujer,29,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Doce de Octubre,Automóvil,Automóvil,Vehículo,2000,Gris,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
1,2019-10-04 03:00:00+00:00,1.0,6.281350,-75.615103,Hombre,46,Unión marital de hecho,Sin dato,Sin dato,Sin dato,...,Conjunto residencial,Doce de Octubre,Camioneta,Camionetas,Vehículo,-1,Blanco,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
2,2020-02-17 11:55:00+00:00,1.0,6.283974,-75.614953,Hombre,36,Soltero(a),Sin dato,Sin dato,Sin dato,...,Parqueadero,Doce de Octubre,Automóvil,Automóvil,Vehículo,2009,Gris,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
3,2020-05-21 02:00:00+00:00,1.0,6.289777,-75.611590,Hombre,18,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Doce de Octubre,Automóvil,Automóvil,Vehículo,2015,Gris,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
4,2020-06-08 18:00:00+00:00,1.0,6.281702,-75.612336,Mujer,57,Soltero(a),Sin dato,Sin dato,Sin dato,...,Parqueadero,Doce de Octubre,Automóvil,Automóvil,Vehículo,1981,Rojo,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2019-05-15 20:30:00+00:00,1.0,6.234816,-75.573827,Hombre,40,Soltero(a),Sin dato,Sin dato,Sin dato,...,Taller mecánico,Candelaria,Camioneta,Camionetas,Vehículo,2015,Beige,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
996,2019-09-04 21:00:00+00:00,1.0,6.230513,-75.569894,Hombre,33,Casado(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Automóvil,Automóvil,Vehículo,2013,Verde,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
997,2020-01-05 15:00:00+00:00,1.0,6.238240,-75.575609,Hombre,36,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Automóvil,Automóvil,Vehículo,2010,Blanco,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
998,2020-07-03 16:30:00+00:00,1.0,6.228413,-75.569976,Mujer,31,Soltero(a),Sin dato,Sin dato,Sin dato,...,Taller mecánico,Candelaria,Automóvil,Automóvil,Vehículo,-1,Plata,Sin dato,Sin dato,2022-06-22 14:12:02+00:00
999,2018-07-07 05:00:00+00:00,1.0,6.229897,-75.570016,Hombre,22,Soltero(a),Sin dato,Sin dato,Sin dato,...,Vía pública,Candelaria,Automóvil,Automóvil,Vehículo,2013,Gris,Sin dato,Sin dato,2022-06-22 14:12:02+00:00

# **DESCARGA DE DATOS**

**Directo al ordenador**

In [15]:
acc.to_csv('/content/drive/MyDrive/accidentes.csv', index = False) # Guardamos el archivo como accidentes.csv
files.download('/content/drive/My Drive/accidentes.csv') # Descargamos el archivo en nuestra maquina local

**Otros formatos**

In [16]:
# Formato pickel: es un formato binario, permite comprimir la información, por lo cual, es util cuando se tienen tablas grandes
acc.to_pickle('/content/drive/My Drive/accidentes.pkl')
acc = pd.read_pickle('/content/drive/My Drive/accidentes.pkl')
acc.head(3)

          FECHA_ACCIDENTE  AÑO_ACCIDENTE MES_ACCIDENTE
0  01/01/2015 12:00:00 AM           2015         enero
1  01/01/2015 12:00:00 AM           2015         enero
2  01/01/2015 12:00:00 AM           2015         enero

In [17]:
# Formato parquet: puede usarse en ambientes de Big Data cuando las bases pertenecen a Apache
acc.to_parquet('/content/drive/My Drive/accidentes.parquet')
acc = pd.read_parquet('/content/drive/My Drive/accidentes.parquet')
acc.head(3)

          FECHA_ACCIDENTE  AÑO_ACCIDENTE MES_ACCIDENTE
0  01/01/2015 12:00:00 AM           2015         enero
1  01/01/2015 12:00:00 AM           2015         enero
2  01/01/2015 12:00:00 AM           2015         enero

In [18]:
# Formato HDFS: puede usarse en ambientes de Big Data con Hadoop
acc.to_hdf('/content/drive/My Drive/accidentes.h5', key = 'acc', format= 'table')
acc = pd.read_hdf('/content/drive/My Drive/accidentes.h5')
acc.head(3)

          FECHA_ACCIDENTE  AÑO_ACCIDENTE MES_ACCIDENTE
0  01/01/2015 12:00:00 AM           2015         enero
1  01/01/2015 12:00:00 AM           2015         enero
2  01/01/2015 12:00:00 AM           2015         enero

Para conocer más formatos nos podemos dirigir a la documentación: 
https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html